languageCode = "en"
languageName = "English"
[languages]
  [languages.en]
    [languages.en.params]
      displayName = 'EN'
      description = "Website about tech"
      rtl = false
      dateFormat = "2 January 2006"
      isoCode = "en"
weight = 1

title = "João Thallis"
# logo = "img/logo.jpg"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  [params.author]
    name = 'João Thallis'
[author]
  image = "img/author.jpeg"
  headline = "I'm a software developer"
  bio = "I am a developer with focus on building scalable and efficient applications." 
  links = [
    { github = "https://github.com/joaothallis" },
    { linkedin = "https://linkedin.com/in/joaothallis" },
    { twitch = "https://twitch.tv/joaothallis2" },
    { youtube = "https://youtube.com/@joaothallis" }
  ]
