languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "João Thallis"

[params]
  dateFormat = "2 January 2006"

  description = "Website about tech"

[params.author]
  name = "João Thallis"
  image = "img/author.jpeg"
  headline = "I'm a software developer"
  bio = "I am a developer with focus on building scalable and efficient applications." 
  links = [
    { github = "https://github.com/joaothallis" },
    { linkedin = "https://linkedin.com/in/joaothallis" },
    { soundcloud = "https://soundcloud.com/joaothallis" },
    { twitch = "https://twitch.tv/joaothallis2" },
    { youtube = "https://youtube.com/@joaothallis" }
  ]
