languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "João Thallis"
# logo = "img/logo.jpg"
description = "Website about tech"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "João Thallis"
  image = "img/author.jpeg"
  headline = "I'm a software developer"
  bio = "I am a developer with focus on building scalable and efficient applications." 
  links = [
    { github = "https://github.com/joaothallis" },
    { linkedin = "https://linkedin.com/in/joaothallis" },
    { twitch = "https://twitch.tv/joaothallis2" },
    { youtube = "https://youtube.com/@joaothallis" }
  ]
