base_url = "https://joaothallis.github.io"
title = "João Thallis"
descrpition = "Blog about software development"

theme = "sam"

compile_sass = true

highlight_code = true

build_search_index = false

check_external_links = true

[extra]
sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "github", link = "https://github.com/joaothallis" }
]
